# Generated by Django 5.1.6 on 2025-02-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advocate',
            new_name='Law',
        ),
    ]
